version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: booksdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  postgres_data: